// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: third/middleware/v1/send/send.proto

package send

import (
	reflect "reflect"
	sync "sync"

	v1 "github.com/NpoolPlatform/kunman/message/basetypes/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject     string        `protobuf:"bytes,10,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Content     string        `protobuf:"bytes,20,opt,name=Content,proto3" json:"Content,omitempty"`
	From        string        `protobuf:"bytes,30,opt,name=From,proto3" json:"From,omitempty"`
	To          string        `protobuf:"bytes,40,opt,name=To,proto3" json:"To,omitempty"`
	ToCCs       []string      `protobuf:"bytes,50,rep,name=ToCCs,proto3" json:"ToCCs,omitempty"`
	ReplyTos    []string      `protobuf:"bytes,60,rep,name=ReplyTos,proto3" json:"ReplyTos,omitempty"`
	AccountType v1.SignMethod `protobuf:"varint,70,opt,name=AccountType,proto3,enum=basetypes.v1.SignMethod" json:"AccountType,omitempty"`
}

func (x *SendMessageInput) Reset() {
	*x = SendMessageInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_middleware_v1_send_send_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageInput) ProtoMessage() {}

func (x *SendMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_third_middleware_v1_send_send_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageInput.ProtoReflect.Descriptor instead.
func (*SendMessageInput) Descriptor() ([]byte, []int) {
	return file_third_middleware_v1_send_send_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageInput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMessageInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageInput) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendMessageInput) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMessageInput) GetToCCs() []string {
	if x != nil {
		return x.ToCCs
	}
	return nil
}

func (x *SendMessageInput) GetReplyTos() []string {
	if x != nil {
		return x.ReplyTos
	}
	return nil
}

func (x *SendMessageInput) GetAccountType() v1.SignMethod {
	if x != nil {
		return x.AccountType
	}
	return v1.SignMethod(0)
}

var File_third_middleware_v1_send_send_proto protoreflect.FileDescriptor

var file_third_middleware_v1_send_send_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2e, 0x6d, 0x69, 0x64,
	0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x1a,
	0x1d, 0x62, 0x61, 0x73, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69,
	0x67, 0x6e, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8,
	0x01, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54,
	0x6f, 0x18, 0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x43, 0x43, 0x73, 0x18, 0x32, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x43, 0x43,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x73, 0x18, 0x3c, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x73, 0x12, 0x3a, 0x0a,
	0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x46, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x0b, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x70, 0x6f, 0x6f, 0x6c, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6b, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_third_middleware_v1_send_send_proto_rawDescOnce sync.Once
	file_third_middleware_v1_send_send_proto_rawDescData = file_third_middleware_v1_send_send_proto_rawDesc
)

func file_third_middleware_v1_send_send_proto_rawDescGZIP() []byte {
	file_third_middleware_v1_send_send_proto_rawDescOnce.Do(func() {
		file_third_middleware_v1_send_send_proto_rawDescData = protoimpl.X.CompressGZIP(file_third_middleware_v1_send_send_proto_rawDescData)
	})
	return file_third_middleware_v1_send_send_proto_rawDescData
}

var (
	file_third_middleware_v1_send_send_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_third_middleware_v1_send_send_proto_goTypes  = []interface{}{
		(*SendMessageInput)(nil), // 0: third.middleware.send.v1.SendMessageInput
		(v1.SignMethod)(0),       // 1: basetypes.v1.SignMethod
	}
)
var file_third_middleware_v1_send_send_proto_depIdxs = []int32{
	1, // 0: third.middleware.send.v1.SendMessageInput.AccountType:type_name -> basetypes.v1.SignMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_third_middleware_v1_send_send_proto_init() }
func file_third_middleware_v1_send_send_proto_init() {
	if File_third_middleware_v1_send_send_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_third_middleware_v1_send_send_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_third_middleware_v1_send_send_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_third_middleware_v1_send_send_proto_goTypes,
		DependencyIndexes: file_third_middleware_v1_send_send_proto_depIdxs,
		MessageInfos:      file_third_middleware_v1_send_send_proto_msgTypes,
	}.Build()
	File_third_middleware_v1_send_send_proto = out.File
	file_third_middleware_v1_send_send_proto_rawDesc = nil
	file_third_middleware_v1_send_send_proto_goTypes = nil
	file_third_middleware_v1_send_send_proto_depIdxs = nil
}
