// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"
	"fmt"

	"github.com/NpoolPlatform/kunman/middleware/billing/db/ent/generated/generated"

	"entgo.io/ent/entql"
	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns an formatted wrapped Allow decision.
func Allowf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Allow)...)
}

// Denyf returns an formatted wrapped Deny decision.
func Denyf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Deny)...)
}

// Skipf returns an formatted wrapped Skip decision.
func Skipf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Skip)...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, ent.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	return f(ctx, q)
}

// MutationRuleFunc type is an adapter which allows the use of
// ordinary functions as mutation rules.
type MutationRuleFunc func(context.Context, ent.Mutation) error

// EvalMutation returns f(ctx, m).
func (f MutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	return f(ctx, m)
}

// QueryMutationRule is an interface which groups query and mutation rules.
type QueryMutationRule interface {
	QueryRule
	MutationRule
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return fixedDecision{Allow}
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return fixedDecision{Deny}
}

type fixedDecision struct {
	decision error
}

func (f fixedDecision) EvalQuery(context.Context, ent.Query) error {
	return f.decision
}

func (f fixedDecision) EvalMutation(context.Context, ent.Mutation) error {
	return f.decision
}

type contextDecision struct {
	eval func(context.Context) error
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return contextDecision{eval}
}

func (c contextDecision) EvalQuery(ctx context.Context, _ ent.Query) error {
	return c.eval(ctx)
}

func (c contextDecision) EvalMutation(ctx context.Context, _ ent.Mutation) error {
	return c.eval(ctx)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op ent.Op) MutationRule {
	return MutationRuleFunc(func(ctx context.Context, m ent.Mutation) error {
		if m.Op().Is(op) {
			return rule.EvalMutation(ctx, m)
		}
		return Skip
	})
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op ent.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m ent.Mutation) error {
		return Denyf("ent/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The AddonQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type AddonQueryRuleFunc func(context.Context, *ent.AddonQuery) error

// EvalQuery return f(ctx, q).
func (f AddonQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AddonQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.AddonQuery", q)
}

// The AddonMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type AddonMutationRuleFunc func(context.Context, *ent.AddonMutation) error

// EvalMutation calls f(ctx, m).
func (f AddonMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.AddonMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.AddonMutation", m)
}

// The ExchangeQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ExchangeQueryRuleFunc func(context.Context, *ent.ExchangeQuery) error

// EvalQuery return f(ctx, q).
func (f ExchangeQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ExchangeQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ExchangeQuery", q)
}

// The ExchangeMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ExchangeMutationRuleFunc func(context.Context, *ent.ExchangeMutation) error

// EvalMutation calls f(ctx, m).
func (f ExchangeMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ExchangeMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ExchangeMutation", m)
}

// The IgnoreIDQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type IgnoreIDQueryRuleFunc func(context.Context, *ent.IgnoreIDQuery) error

// EvalQuery return f(ctx, q).
func (f IgnoreIDQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.IgnoreIDQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.IgnoreIDQuery", q)
}

// The IgnoreIDMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type IgnoreIDMutationRuleFunc func(context.Context, *ent.IgnoreIDMutation) error

// EvalMutation calls f(ctx, m).
func (f IgnoreIDMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.IgnoreIDMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.IgnoreIDMutation", m)
}

// The PubsubMessageQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type PubsubMessageQueryRuleFunc func(context.Context, *ent.PubsubMessageQuery) error

// EvalQuery return f(ctx, q).
func (f PubsubMessageQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PubsubMessageQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.PubsubMessageQuery", q)
}

// The PubsubMessageMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type PubsubMessageMutationRuleFunc func(context.Context, *ent.PubsubMessageMutation) error

// EvalMutation calls f(ctx, m).
func (f PubsubMessageMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.PubsubMessageMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.PubsubMessageMutation", m)
}

// The SubscriptionQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type SubscriptionQueryRuleFunc func(context.Context, *ent.SubscriptionQuery) error

// EvalQuery return f(ctx, q).
func (f SubscriptionQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubscriptionQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.SubscriptionQuery", q)
}

// The SubscriptionMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type SubscriptionMutationRuleFunc func(context.Context, *ent.SubscriptionMutation) error

// EvalMutation calls f(ctx, m).
func (f SubscriptionMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.SubscriptionMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.SubscriptionMutation", m)
}

// The UserCreditRecordQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserCreditRecordQueryRuleFunc func(context.Context, *ent.UserCreditRecordQuery) error

// EvalQuery return f(ctx, q).
func (f UserCreditRecordQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserCreditRecordQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.UserCreditRecordQuery", q)
}

// The UserCreditRecordMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserCreditRecordMutationRuleFunc func(context.Context, *ent.UserCreditRecordMutation) error

// EvalMutation calls f(ctx, m).
func (f UserCreditRecordMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.UserCreditRecordMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.UserCreditRecordMutation", m)
}

// The UserSubscriptionQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserSubscriptionQueryRuleFunc func(context.Context, *ent.UserSubscriptionQuery) error

// EvalQuery return f(ctx, q).
func (f UserSubscriptionQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.UserSubscriptionQuery", q)
}

// The UserSubscriptionMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserSubscriptionMutationRuleFunc func(context.Context, *ent.UserSubscriptionMutation) error

// EvalMutation calls f(ctx, m).
func (f UserSubscriptionMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.UserSubscriptionMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.UserSubscriptionMutation", m)
}

// The UserSubscriptionChangeQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserSubscriptionChangeQueryRuleFunc func(context.Context, *ent.UserSubscriptionChangeQuery) error

// EvalQuery return f(ctx, q).
func (f UserSubscriptionChangeQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserSubscriptionChangeQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.UserSubscriptionChangeQuery", q)
}

// The UserSubscriptionChangeMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserSubscriptionChangeMutationRuleFunc func(context.Context, *ent.UserSubscriptionChangeMutation) error

// EvalMutation calls f(ctx, m).
func (f UserSubscriptionChangeMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.UserSubscriptionChangeMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.UserSubscriptionChangeMutation", m)
}

type (
	// Filter is the interface that wraps the Where function
	// for filtering nodes in queries and mutations.
	Filter interface {
		// Where applies a filter on the executed query/mutation.
		Where(entql.P)
	}

	// The FilterFunc type is an adapter that allows the use of ordinary
	// functions as filters for query and mutation types.
	FilterFunc func(context.Context, Filter) error
)

// EvalQuery calls f(ctx, q) if the query implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	fr, err := queryFilter(q)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

// EvalMutation calls f(ctx, q) if the mutation implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	fr, err := mutationFilter(m)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

var _ QueryMutationRule = FilterFunc(nil)

func queryFilter(q ent.Query) (Filter, error) {
	switch q := q.(type) {
	case *ent.AddonQuery:
		return q.Filter(), nil
	case *ent.ExchangeQuery:
		return q.Filter(), nil
	case *ent.IgnoreIDQuery:
		return q.Filter(), nil
	case *ent.PubsubMessageQuery:
		return q.Filter(), nil
	case *ent.SubscriptionQuery:
		return q.Filter(), nil
	case *ent.UserCreditRecordQuery:
		return q.Filter(), nil
	case *ent.UserSubscriptionQuery:
		return q.Filter(), nil
	case *ent.UserSubscriptionChangeQuery:
		return q.Filter(), nil
	default:
		return nil, Denyf("ent/privacy: unexpected query type %T for query filter", q)
	}
}

func mutationFilter(m ent.Mutation) (Filter, error) {
	switch m := m.(type) {
	case *ent.AddonMutation:
		return m.Filter(), nil
	case *ent.ExchangeMutation:
		return m.Filter(), nil
	case *ent.IgnoreIDMutation:
		return m.Filter(), nil
	case *ent.PubsubMessageMutation:
		return m.Filter(), nil
	case *ent.SubscriptionMutation:
		return m.Filter(), nil
	case *ent.UserCreditRecordMutation:
		return m.Filter(), nil
	case *ent.UserSubscriptionMutation:
		return m.Filter(), nil
	case *ent.UserSubscriptionChangeMutation:
		return m.Filter(), nil
	default:
		return nil, Denyf("ent/privacy: unexpected mutation type %T for mutation filter", m)
	}
}
