// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.1
// source: version/version.proto

package v1

import (
	context "context"
	v1 "github.com/NpoolPlatform/kunman/message/basetypes/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Kunman_Version_FullMethodName = "/version.v1.Kunman/Version"
)

// KunmanClient is the client API for Kunman service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KunmanClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.VersionResponse, error)
}

type kunmanClient struct {
	cc grpc.ClientConnInterface
}

func NewKunmanClient(cc grpc.ClientConnInterface) KunmanClient {
	return &kunmanClient{cc}
}

func (c *kunmanClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.VersionResponse, error) {
	out := new(v1.VersionResponse)
	err := c.cc.Invoke(ctx, Kunman_Version_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KunmanServer is the server API for Kunman service.
// All implementations must embed UnimplementedKunmanServer
// for forward compatibility
type KunmanServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*v1.VersionResponse, error)
	mustEmbedUnimplementedKunmanServer()
}

// UnimplementedKunmanServer must be embedded to have forward compatible implementations.
type UnimplementedKunmanServer struct {
}

func (UnimplementedKunmanServer) Version(context.Context, *emptypb.Empty) (*v1.VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedKunmanServer) mustEmbedUnimplementedKunmanServer() {}

// UnsafeKunmanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KunmanServer will
// result in compilation errors.
type UnsafeKunmanServer interface {
	mustEmbedUnimplementedKunmanServer()
}

func RegisterKunmanServer(s grpc.ServiceRegistrar, srv KunmanServer) {
	s.RegisterService(&Kunman_ServiceDesc, srv)
}

func _Kunman_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KunmanServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kunman_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KunmanServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Kunman_ServiceDesc is the grpc.ServiceDesc for Kunman service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kunman_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "version.v1.Kunman",
	HandlerType: (*KunmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Kunman_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version/version.proto",
}
