// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: basetypes/agi/v1/enums.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageType int32

const (
	UsageType_DefaultUsageType UsageType = 0
	UsageType_TextToken        UsageType = 10
	UsageType_ChatCount        UsageType = 20
	UsageType_ImageCount       UsageType = 30
	UsageType_VideoCount       UsageType = 40
	UsageType_FilePageCount    UsageType = 50
)

// Enum value maps for UsageType.
var (
	UsageType_name = map[int32]string{
		0:  "DefaultUsageType",
		10: "TextToken",
		20: "ChatCount",
		30: "ImageCount",
		40: "VideoCount",
		50: "FilePageCount",
	}
	UsageType_value = map[string]int32{
		"DefaultUsageType": 0,
		"TextToken":        10,
		"ChatCount":        20,
		"ImageCount":       30,
		"VideoCount":       40,
		"FilePageCount":    50,
	}
)

func (x UsageType) Enum() *UsageType {
	p := new(UsageType)
	*p = x
	return p
}

func (x UsageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsageType) Descriptor() protoreflect.EnumDescriptor {
	return file_basetypes_agi_v1_enums_proto_enumTypes[0].Descriptor()
}

func (UsageType) Type() protoreflect.EnumType {
	return &file_basetypes_agi_v1_enums_proto_enumTypes[0]
}

func (x UsageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsageType.Descriptor instead.
func (UsageType) EnumDescriptor() ([]byte, []int) {
	return file_basetypes_agi_v1_enums_proto_rawDescGZIP(), []int{0}
}

type CapacityKey int32

const (
	CapacityKey_DefaultCapacityKey CapacityKey = 0
	CapacityKey_CapacityQPS        CapacityKey = 10
)

// Enum value maps for CapacityKey.
var (
	CapacityKey_name = map[int32]string{
		0:  "DefaultCapacityKey",
		10: "CapacityQPS",
	}
	CapacityKey_value = map[string]int32{
		"DefaultCapacityKey": 0,
		"CapacityQPS":        10,
	}
)

func (x CapacityKey) Enum() *CapacityKey {
	p := new(CapacityKey)
	*p = x
	return p
}

func (x CapacityKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapacityKey) Descriptor() protoreflect.EnumDescriptor {
	return file_basetypes_agi_v1_enums_proto_enumTypes[1].Descriptor()
}

func (CapacityKey) Type() protoreflect.EnumType {
	return &file_basetypes_agi_v1_enums_proto_enumTypes[1]
}

func (x CapacityKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapacityKey.Descriptor instead.
func (CapacityKey) EnumDescriptor() ([]byte, []int) {
	return file_basetypes_agi_v1_enums_proto_rawDescGZIP(), []int{1}
}

var File_basetypes_agi_v1_enums_proto protoreflect.FileDescriptor

var file_basetypes_agi_v1_enums_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x62, 0x61, 0x73, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x61, 0x67, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x62, 0x61, 0x73, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x61, 0x67, 0x69, 0x2e, 0x76, 0x31,
	0x2a, 0x72, 0x0a, 0x09, 0x55, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x10, 0x0a, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10,
	0x14, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10,
	0x1e, 0x12, 0x0e, 0x0a, 0x0a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10,
	0x28, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x10, 0x32, 0x2a, 0x36, 0x0a, 0x0b, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x61,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x51, 0x50, 0x53, 0x10, 0x0a, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x70, 0x6f, 0x6f, 0x6c,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6b, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x61, 0x67, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_basetypes_agi_v1_enums_proto_rawDescOnce sync.Once
	file_basetypes_agi_v1_enums_proto_rawDescData = file_basetypes_agi_v1_enums_proto_rawDesc
)

func file_basetypes_agi_v1_enums_proto_rawDescGZIP() []byte {
	file_basetypes_agi_v1_enums_proto_rawDescOnce.Do(func() {
		file_basetypes_agi_v1_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_basetypes_agi_v1_enums_proto_rawDescData)
	})
	return file_basetypes_agi_v1_enums_proto_rawDescData
}

var file_basetypes_agi_v1_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_basetypes_agi_v1_enums_proto_goTypes = []interface{}{
	(UsageType)(0),   // 0: basetypes.agi.v1.UsageType
	(CapacityKey)(0), // 1: basetypes.agi.v1.CapacityKey
}
var file_basetypes_agi_v1_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basetypes_agi_v1_enums_proto_init() }
func file_basetypes_agi_v1_enums_proto_init() {
	if File_basetypes_agi_v1_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_basetypes_agi_v1_enums_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basetypes_agi_v1_enums_proto_goTypes,
		DependencyIndexes: file_basetypes_agi_v1_enums_proto_depIdxs,
		EnumInfos:         file_basetypes_agi_v1_enums_proto_enumTypes,
	}.Build()
	File_basetypes_agi_v1_enums_proto = out.File
	file_basetypes_agi_v1_enums_proto_rawDesc = nil
	file_basetypes_agi_v1_enums_proto_goTypes = nil
	file_basetypes_agi_v1_enums_proto_depIdxs = nil
}
