// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: appuser/gateway/v1/gateway.proto

package v1

import (
	reflect "reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_appuser_gateway_v1_gateway_proto protoreflect.FileDescriptor

var file_appuser_gateway_v1_gateway_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x70, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x32, 0x09, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4e, 0x70, 0x6f, 0x6f, 0x6c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6b, 0x75,
	0x6e, 0x6d, 0x61, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x70,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appuser_gateway_v1_gateway_proto_goTypes = []interface{}{}
	file_appuser_gateway_v1_gateway_proto_depIdxs = []int32{
		0, // [0:0] is the sub-list for method output_type
		0, // [0:0] is the sub-list for method input_type
		0, // [0:0] is the sub-list for extension type_name
		0, // [0:0] is the sub-list for extension extendee
		0, // [0:0] is the sub-list for field type_name
	}
)

func init() { file_appuser_gateway_v1_gateway_proto_init() }
func file_appuser_gateway_v1_gateway_proto_init() {
	if File_appuser_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appuser_gateway_v1_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appuser_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_appuser_gateway_v1_gateway_proto_depIdxs,
	}.Build()
	File_appuser_gateway_v1_gateway_proto = out.File
	file_appuser_gateway_v1_gateway_proto_rawDesc = nil
	file_appuser_gateway_v1_gateway_proto_goTypes = nil
	file_appuser_gateway_v1_gateway_proto_depIdxs = nil
}
